### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by MartinSzollos2016** [h4kuna/ares#11]
Could you consider using cache for ares requests ?

**Comment by h4kuna** [comment]
Ares had easy memory cache in the past. I am not sure if is need. Because, you get result like Data object and this result you can cache your self. Nette, Symfony, Laravel whatever has different cache implementation. Cache is next level. How many times per one day download same info by identification number? Probably every time is unique. May be twotimes threetimes?

**Comment by h4kuna** [comment]
You can try [memoize](/h4kuna/memoize)
